Adding optional "family" string property to events.
ocsf/ocsf-validator pull request #37
Opened 2024-12-10 17:54 UTC by query-jeremy

This adds the new `family` property of events to the types definition to fix a failing unrecognized key check in `ocsf-schema` #1260.

2024-12-10 22:22 UTC, alanisaac approved these changes
Looks good!

2024-12-11 00:30 UTC, pagbabian-splunk approved these changes

2024-12-11 02:12 UTC, rmouritzen-splunk commented
This is a duplicate of https://github.com/ocsf/ocsf-validator/pull/36 - which do we want to keep?

2024-12-11 02:14 UTC, rmouritzen-splunk requested changes
This is identical to the existing prior PR https://github.com/ocsf/ocsf-validator/pull/36 -- which one do we want to keep?

2024-12-13 19:30 UTC, merged